sudo: required

language: python
python:
  #- "2.6"
  #- "2.7"
  #- "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install: 
  - "pip install -r requirements.txt"
  - "pip install pytest pytest-cov python-coveralls"
  
before_script:
  - docker pull mongo:3.4.6
  - docker run -d -p 127.0.0.1:27017:27017 mongo:3.4.6
  - docker ps -a

env:
  - MONGODB_NAME=wispysvr MONGODB_HOST=localhost MONGODB_PORT=27017 

# command to run tests
script: py.test test/ --cov=wispysvr --cov=db

after_success:
  coveralls
  