# Wispysvr 

version: '3'
services:
  wispysvr:
      build: .
      ports:
        - "3003:5000"
      volumes:
        - .:/wispysvr
      environment:
        - PYTHONUNBUFFERED=0
        - MONGODB_NAME=wispysvr
        - MONGODB_HOST=wispysvrdb
        - MONGODB_PORT=27017
      command: sh -c "py.test -v test/ --cov=wispysvr --cov=db"
      #command: sh -c "python wispysvr.py"
  wispysvrdb:
      image: "mongo:3.4.6"
      ports:
        - "3004:27017"
  